networks:
  net:
    driver: overlay
    attachable: true

version: '3.5'

services:
  back:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net
    ports:
      - 3001:3000
    environment:
      DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@back-proxy_postgres_1:5432/${POSTGRES_DB}?schema=public'
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - net

volumes:
  redis-data:
  postgres_data:
